# AppVeyor for Pyslvs-UI
image: Visual Studio 2019
platform: x64

environment:
  MSYS_DIR: C:\msys64
  matrix:
    - PYTHON_DIR: C:\Python36-x64
    - PYTHON_DIR: C:\Python37-x64

install:
  # Environment variables
  - set Path=%MSYS_DIR%\mingw64\bin;%MSYS_DIR%\usr\bin;%Path%
  - set Path=%PYTHON_DIR%;%PYTHON_DIR%\Scripts;%Path%
  # Show Python
  - python --version
  - pip --version
  # Upgrade setuptools
  - pip install setuptools -U
  # Set Python compiler to MinGW
  - platform\set_pycompiler %PYTHON_DIR%
  # Install modules
  - pip install -r requirements.txt
  # Show tool kits
  - gcc --version
  - mingw32-make --version

before_build:
  # Clone submodules
  - git submodule update --init --recursive

build_script:
  - python setup.py test

artifacts:
  - path: dist\*.whl

deploy_script:
  # PyPI deployment
  - IF "%APPVEYOR_REPO_TAG%"=="true"
    IF "%APPVEYOR_REPO_NAME%"=="KmolYuan/pyslvs" (
    pip install twine &&
    python setup.py bdist_wheel &&
    twine upload dist\*.whl --skip-existing
    )
