# AppVeyor for Pyslvs-UI
version: '{build}'
image: Visual Studio 2019
platform: x64
clone_depth: 1
environment:
  MSYS_DIR: C:\msys64
  matrix:
    - PYTHON_DIR: C:\Python37-x64
      COMPILER: mingw32
      # Cython issue
#    - PYTHON_DIR: C:\Python38-x64
#      COMPILER: mingw32
    - PYTHON_DIR: C:\Python38-x64
      COMPILER: msvc

install:
  # Clone submodules
  - git submodule update --init --recursive
  # Install Python-dev
  - IF DEFINED PYTHON_DEV choco install -y python --version %PYTHON_DEV%
  # Environment variables
  - set Path=%MSYS_DIR%\mingw64\bin;%MSYS_DIR%\usr\bin;%Path%
  - set Path=%PYTHON_DIR%;%PYTHON_DIR%\Scripts;%Path%
  # Show Python
  - python --version
  - pip --version
  # Upgrade setuptools
  - pip install setuptools -U
  # Set Python compiler to MinGW
  - platform\set_pycompiler %PYTHON_DIR% %COMPILER%
  # Install modules
  - pip install -r requirements.txt

build_script:
  - python setup.py test

after_build:
  # PyPI deployment
  - IF "%APPVEYOR_REPO_TAG%"=="true"
    IF "%APPVEYOR_REPO_NAME%"=="KmolYuan/pyslvs" (
    pip install twine &&
    python setup.py bdist_wheel &&
    twine upload dist\*.whl --skip-existing
    )
